.\" Copyright (c) 2022 Stijn van Dongen
.TH "clm vol" 1 "9 Oct 2022" "clm vol 22-282" "USER COMMANDS "
.po 2m
.de ZI
.\" Zoem Indent/Itemize macro I.
.br
'in +\\$1
.nr xa 0
.nr xa -\\$1
.nr xb \\$1
.nr xb -\\w'\\$2'
\h'|\\n(xau'\\$2\h'\\n(xbu'\\
..
.de ZJ
.br
.\" Zoem Indent/Itemize macro II.
'in +\\$1
'in +\\$2
.nr xa 0
.nr xa -\\$2
.nr xa -\\w'\\$3'
.nr xb \\$2
\h'|\\n(xau'\\$3\h'\\n(xbu'\\
..
.if n .ll -2m
.am SH
.ie n .in 4m
.el .in 8m
..
.SH NAME
clm vol \- compute volatile nodes from a set of clusterings

clmvol is not in actual fact a program\&. This manual
page documents the behaviour and options of the clm program when
invoked in mode \fIvol\fP\&. The options \fB-h\fP, \fB--apropos\fP,
\fB--version\fP, \fB-set\fP, \fB--nop\fP are accessible
in all \fBclm\fP modes\&. They are described
in the \fBclm\fP manual page\&.
.SH SYNOPSIS

\fBclm vol\fP
\fB[-o\fP fname (\fIoutput file\fP)\fB]\fP
\fB[-imx\fP fname (\fIread network\fP)\fB]\fP
\fB[--self\fP (\fIinclude self-comparisons\fP)\fB]\fP
\fB[-write-rcl\fP fname (\fIwrite rcl network\fP)\fB]\fP
<cl file>+
.SH DESCRIPTION

\fBclm vol\fP computes a score for each node, which is expressed as a promille\&.
The output is in the form of a matrix containing a single column\&. The score
inversely correlates with what is deemed to be volatile behaviour\&. For all pairs of
clusterings the set of all intersections is computed, and these are
considered in turn\&.

The list of cluster files can be split in two parts by inserting a double
hyphen (\fC--\fP) inbetween the parts\&. Comparisons will be between all pairs
where one clustering is in the first part and the other clustering is in the
second part\&.
.SH AUTHOR

Stijn van Dongen\&.
.SH OPTIONS

.ZI 2m "\fB-o\fP fname (\fIoutput file\fP)"
\&
.br
.in -2m

.ZI 2m "\fB-imx\fP fname (\fIread network\fP)"
\&
.br
.in -2m

.ZI 2m "\fB-write-rcl\fP fname (\fIwrite rcl network\fP)"
\&
'in -2m
.ZI 2m "\fB--self\fP (\fIinclude self-comparisons\fP)"
\&
'in -2m
'in +2m
\&
.br
Specifying the file name causes the Restricted Contingency Linkage network to be computed
and saved to that file\&. If \fB--self\fP is specified each clusters is compared to itself
as well as to other clusterings, effectively incorporating the standard cluster co-ocurrence
edge weight as a contribution to the RCL network\&.
.in -2m
.SH SEE ALSO

\fBmclfamily(7)\fP for an overview of all the documentation
and the utilities in the mcl family\&.
